### ISSUE TITLE
Permissionless Asset registry checklist

### ISSUE THREAD

**Issue by blasrodri** [ComposableFi/composable#3799]
We need to point to the new subxt types so that the relayer is upgraded
root@centauri-devnet:~/composable# git diff code/Cargo.toml

```diff
diff --git a/code/Cargo.toml b/code/Cargo.toml
index 137ad3ff8..b537d5e45 100644
--- a/code/Cargo.toml
+++ b/code/Cargo.toml
@@ -108,12 +108,12 @@ orml-xcm-support = { git = "https://github.com/open-web3-stack/open-runtime-modu
 orml-xtokens = { git = "https://github.com/open-web3-stack/open-runtime-module-library", rev = "a0751540591c88ccc2d4029464de887933727183", default-features = false }
 orml-tokens = { git = "https://github.com/open-web3-stack/open-runtime-module-library", rev = "a0751540591c88ccc2d4029464de887933727183", default-features = false }
 
-ibc = { git = "https://github.com/ComposableFi/centauri", rev = "9e567ab1d55e4ec0dbad9400fb2bbec177a1896b", default-features = false }
-ibc-rpc = { git = "https://github.com/ComposableFi/centauri", rev = "9e567ab1d55e4ec0dbad9400fb2bbec177a1896b", default-features = false }
-ibc-primitives = { git = "https://github.com/ComposableFi/centauri", rev = "9e567ab1d55e4ec0dbad9400fb2bbec177a1896b", default-features = false }
-ibc-runtime-api = { git = "https://github.com/ComposableFi/centauri", rev = "9e567ab1d55e4ec0dbad9400fb2bbec177a1896b", default-features = false }
-pallet-ibc = { git = "https://github.com/ComposableFi/centauri", rev = "9e567ab1d55e4ec0dbad9400fb2bbec177a1896b", default-features = false }
-pallet-ibc-ping = { git = "https://github.com/ComposableFi/centauri", rev = "9e567ab1d55e4ec0dbad9400fb2bbec177a1896b", default-features = false }
+ibc = { git = "https://github.com/ComposableFi/centauri", rev = "19ac03b58a28f3e644c125d3109c5a7a2db1b6cf", default-features = false }
+ibc-rpc = { git = "https://github.com/ComposableFi/centauri", rev = "19ac03b58a28f3e644c125d3109c5a7a2db1b6cf", default-features = false }
+ibc-primitives = { git = "https://github.com/ComposableFi/centauri", rev = "19ac03b58a28f3e644c125d3109c5a7a2db1b6cf", default-features = false }
+ibc-runtime-api = { git = "https://github.com/ComposableFi/centauri", rev = "19ac03b58a28f3e644c125d3109c5a7a2db1b6cf", default-features = false }
+pallet-ibc = { git = "https://github.com/ComposableFi/centauri", rev = "19ac03b58a28f3e644c125d3109c5a7a2db1b6cf", default-features = false }
+pallet-ibc-ping = { git = "https://github.com/ComposableFi/centauri", rev = "19ac03b58a28f3e644c125d3109c5a7a2db1b6cf", default-features = false }
 
 xcm-builder = { git = "https://github.com/paritytech/polkadot", rev = "c22e1c4173bf6966f5d1980f4299f7abe836f0c1", default-features = false }
 polkadot-primitives = { git = "https://github.com/paritytech/polkadot", rev = "c22e1c4173bf6966f5d1980f4299f7abe836f0c1", default-features = false }
```
One way to do this, is to run 
- .#zombienet-picasso-centauri-a and .#zombienet-picasso-centauri-b
- Create client, connection and channel between these two parachains manually.
- Perform an ics20 transfer
- Do the asset migration
- Perform an ics20 transfer

Relayer config

`config-a.toml`
```toml
type = "parachain"
name = "picasso"
para_id = 2087
parachain_rpc_url = "ws://127.0.0.1:9988"
relay_chain_rpc_url = "ws://127.0.0.1:9944"
client_id = "10-grandpa-0"
connection_id = "connection-0"
channel_whitelist = []
commitment_prefix = "0x6962632f"
private_key = "//Alice"
ss58_version = 49
key_type = "sr25519"
finality_protocol = "Grandpa"
```

`config-b.toml`
```toml
type = "parachain"
name = "picasso"
para_id = 2087
parachain_rpc_url = "ws://127.0.0.1:29988"
relay_chain_rpc_url = "ws://127.0.0.1:29944"
client_id = "10-grandpa-0"
connection_id = "connection-0"
channel_whitelist = []
commitment_prefix = "0x6962632f"
private_key = "//Alice"
ss58_version = 49
key_type = "sr25519"
finality_protocol = "Grandpa"
```

`config-core.toml`
```toml
prometheus_endpoint = "https://127.0.0.1"
```
